#!/bin/bash

# Basic configuration
bspc config border_width 1 
bspc config window_gap 15

bspc config focus_follows_pointer true
bspc config pointer_motion_interval 10

# Remove a monitor if disabled or unplugged
bspc config remove_disabled_monitor true
bspc config remove_unplugged_monitor true
bspc config merge_overlapping_monitors true

# Setup monitors with xrandr
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rate 144.00 --output HDMI-A-0 --mode 1920x1080 --rate 75.00 --right-of DisplayPort-0

# Get a normal cursor
xsetroot -cursor_name left_ptr &

# Monitors
bspc monitor DisplayPort-0 -d 1 2 3 4 5 &
bspc monitor HDMI-A-0 -d 6 7 8 9 0 &

# Manager for screen locking
xss-lock xsecurelock &

# Start sxhkd
killall sxhkd
sxhkd &

# Start Redshift
redshift-gtk &

# Policy kit
/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Polybar
~/.config/polybar/launch.sh &

# Restore nitrogen configuration
nitrogen --restore

# Start picom
picom & 

# Network-Manager applet
nm-applet &

# Dunst
dunst &

# Xsettingsd
xsettingsd &

# Autostart (for desktop applications)
~/.config/bspwm/autostart.sh &
